version:     "0018b--03-Aug-2021"
copyright:   "2021-2021"
description:
  This is my
  GitHub Page for OS212
disclaimer:
  I have spoken.
keywords:    "jekyll, testing"
navbarlinks:
- navbar:    "Home"
  link:      "/"
- navbar:    "Links"
  link:      "/LINKS/"
- navbar:    "Tips"
  link:      "/TIPS/"
- navbar:    "GitHub"
  link:      "https://github.com/tanpeep/os212/"
- navbar:    "Listing"
  link:      "/000.html"
- navbar:    "Log"
  link:      "https://tanpeep.github.io/os212/TXT/mylog.txt"
- navbar:    "About"
  link:      "/ABOUT/"
title:       "tanpeep | os212"
lang:        "en-US"
author:      "tanpeep"
address:     "Depok"
sitemap:     "true"
markdown:    "kramdown"
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata
plugins:
- jekyll-sitemap
- jekyll-seo-tag
google_analytics: "UA-89852122-15"

urlweb:           "https://template.vlsm.org/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/tanpeep/os212/"


